title: 'BitDevs em Português'
tagline: 'BitDevs é uma comunidade para aqueles interessados em discutir e participar na pesquisa e desenvolvimento do Bitcoin e protocolos relacionados.'

menu:

  - {name: 'Eventos', url: '/events'}
  - {name: 'Meetup', url: 'https://www.meetup.com/Bitcoin-Assembly/', external: true}
